#
# Makefile for the Cypress touchkey driver
#

obj-$(CONFIG_KEYBOARD_CYPRESS_TOUCH) += cypress-touchkey.o issp_main.o issp_routines.o issp_driver_routines.o next_fw_update.o
obj-$(CONFIG_KEYBOARD_CYPRESS_TOUCH_236) += cypress-touchkey-236.o issp_main.o issp_routines.o issp_driver_routines.o
