#
# Compass Slaves MPUxxxx
#
obj-$(CONFIG_MPU_SENSORS_AK8975_411) += inv_mpu_ak8975.o
inv_mpu_ak8975-objs +=	ak8975.o

EXTRA_CFLAGS += -Idrivers/misc/inv_mpu
EXTRA_CFLAGS += -D__C99_DESIGNATED_INITIALIZER
