#
#  Makefile for the kernel Sensor device drivers.
#

obj-$(CONFIG_SENSORS_CORE)		+= sensors_core.o
obj-$(CONFIG_SENSORS_ALPS)		+= alps-input.o
obj-$(CONFIG_SENSORS_ALPS_MAG_HSCDTD008A)			+= hscdtd008a_i2c.o
obj-$(CONFIG_SENSORS_ALPS_ACC_BMA254)	+= alps_acc_bma254.o
obj-$(CONFIG_PROXIMITY_SENSOR)	+= gp2a.o
